"""Command-line entry point for meeting-notes."""

from __future__ import annotations

import argparse
import sys
from collections.abc import Sequence
from pathlib import Path

from meeting_notes import __version__
from meeting_notes.errors import MeetingNotesError
from meeting_notes.media import (
    ensure_system_dependencies,
    probe_recording,
    render_inspection,
)
from meeting_notes.pipeline import ProcessOptions, run_process


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="meeting-notes",
        description=(
            "Transcribe OBS meeting recordings locally with MLX Whisper on Apple Silicon "
            "macOS or OpenAI Whisper on Linux."
        ),
    )
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    subparsers = parser.add_subparsers(dest="command", required=True)

    inspect_parser = subparsers.add_parser(
        "inspect", help="inspect container and OBS audio stream layout with ffprobe"
    )
    inspect_parser.add_argument("recording", type=Path, help="path to a local OBS recording")
    inspect_parser.add_argument("--verbose", action="store_true", help="show additional details")

    process_parser = subparsers.add_parser(
        "process", help="extract audio and create local timestamped transcript artifacts"
    )
    process_parser.add_argument("recording", type=Path, help="path to a local OBS recording")
    process_parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("output"),
        metavar="DIR",
        help="artifact root directory (default: ./output)",
    )
    process_parser.add_argument("--model", help="override the platform's default Whisper model")
    process_parser.add_argument(
        "--language", metavar="CODE", help="spoken language hint, such as en or es (default: auto)"
    )
    process_parser.add_argument(
        "--speaker-mode",
        choices=("auto", "mixed", "obs-3track"),
        default="auto",
        help="speaker labelling strategy (default: auto)",
    )
    process_parser.add_argument(
        "--me-name",
        default="Me",
        help="label for OBS microphone-track segments (default: Me)",
    )
    process_parser.add_argument(
        "--keep-audio",
        action="store_true",
        help=(
            "keep extracted WAVs from a new transcription; use --force to recreate them "
            "for a resumed transcript"
        ),
    )
    process_parser.add_argument(
        "--no-summary",
        action="store_true",
        help="transcribe only; summary-prompt.md is still generated for later use",
    )
    process_parser.add_argument(
        "--force",
        action="store_true",
        help="rerun Whisper in a new collision-safe run directory",
    )
    process_parser.add_argument("--verbose", action="store_true", help="show additional details")
    return parser


def _progress(message: str) -> None:
    print(message, file=sys.stderr, flush=True)


def _run_inspect(args: argparse.Namespace) -> int:
    ensure_system_dependencies()
    info = probe_recording(args.recording, verbose=bool(args.verbose))
    print(render_inspection(info), end="")
    return 0


def _run_process(args: argparse.Namespace) -> int:
    result = run_process(
        ProcessOptions(
            recording=args.recording,
            output_root=args.output_dir,
            model=args.model,
            language=args.language,
            speaker_mode=args.speaker_mode,
            me_name=args.me_name,
            keep_audio=bool(args.keep_audio),
            no_summary=bool(args.no_summary),
            force=bool(args.force),
            verbose=bool(args.verbose),
        ),
        progress=_progress,
    )
    print("Done.")
    print(f"Run directory: {result.run_directory}")
    print(f"Transcript: {result.transcript_path}")
    print(f"Summary prompt: {result.prompt_path}")
    print(f"Backend: {result.backend.name}")
    print(f"Device: {result.backend.device_label}")
    print(f"Model: {result.backend.model}")
    if result.resumed:
        print("Whisper: skipped (valid matching transcript already exists)")
    if args.no_summary:
        print("Summary: not generated (--no-summary)")
    else:
        print("Summary: not generated by this CLI; use the shared process-meeting Agent Skill")
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        if args.command == "inspect":
            return _run_inspect(args)
        if args.command == "process":
            return _run_process(args)
    except MeetingNotesError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2
    except OSError as exc:
        print(f"Error: local filesystem operation failed: {exc}", file=sys.stderr)
        return 2
    except KeyboardInterrupt:
        print("Interrupted.", file=sys.stderr)
        return 130
    raise AssertionError(f"unexpected command: {args.command}")


if __name__ == "__main__":
    raise SystemExit(main())
